services:
  - type: web
    name: calorie-tracker-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false # This means you need to set this manually in Render dashboard 